version: "3.7"
services:
  app:
    build:
      args:
        user: bridge2web
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: k-telecom
    container_name: k-telecom-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - k-telecom
  db:
    image: mysql:5.7
    container_name: k-telecom-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    command: --character-set-server=utf8 --collation-server=utf8_unicode_ci
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
    networks:
      - k-telecom

  nginx:
    image: nginx:alpine
    container_name: k-telecom-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d
    networks:
      - k-telecom

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      PMA_ARBITRARY: 1
    networks:
      - k-telecom

networks:
  k-telecom:
    driver: bridge
